# Generated by Django 4.2.4 on 2025-07-21 22:53

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicekey',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
